### ISSUE TITLE
Feature request: Recognise exported global constants

### ISSUE THREAD

**Issue by lydia-roberts** [sverweij/eslint-plugin-budapestian#18]
Current global constant rule does not recognise constants prefixed with `export`

### Context

My team often stores constants in a global constants file which will look like this
```
export const MY_GLOBAL_CONSTANT = 'something';
```

### Expected Behavior

The rule should recognise this as a global const and ensure it is in UPPER_SNAKE_CASE

### Current Behavior

The rule does recognise this as a global const and allows camelCase

**Comment by sverweij** [comment]
Hi @lydia-roberts - thanks for raising this issue! I'll expand the rule; the mere fact a `const` gets `export`ed shouldn't bock it from getting flagged.

**Comment by lydia-roberts** [comment]
Hey @sverweij - I just tried out the beta version and it works as expected. Thank you for such a quick fix!

**Comment by sverweij** [comment]
Thanks for the quick validation @lydia-roberts.

B.t.w. I realised this change is _breaking_ as formerly non-flagged items will now be flagged without changes in the rule - so this will be released as version 4.0.0. I'll give a heads-up in this thread on/ directly after publication.

**Comment by sverweij** [comment]
Hi @lydia-roberts eslint-plugin-budapestian@4.0.0 with the fix is now on npmjs.

**Comment by lydia-roberts** [comment]
Brilliant, thanks. @sverweij. 

Those defaults make sense to me but we also don't tend to use arrow functions or `require` since we mostly use typescript
